#!/bin/bash

# This post-checkout hook ensures the version of the sampleDB
# that is installed is compatible with the code in the branch.

REPO_ROOT_DIR=$(git rev-parse --show-toplevel)
source "$REPO_ROOT_DIR/bin/lib.bash"

FROM_REF=$1
TO_REF=$2
IS_FILE=$3

# Don't run this when a repo is cloned.
if [ -z "$FROM_REF" ]; then
  exit 0
fi

# Don't run this if there are no changes (e.g. switching to a new branch).
if [ "$FROM_REF" = "$TO_REF" ]; then
  exit 0
fi

# Don't run this if this is a file checkout.
if [ ! "$IS_FILE" ]; then
  exit 0
fi

echo "Running FarmData2 post-checkout hook..."

DB_VERSION=$(head -1 "$REPO_ROOT_DIR"/.fd2dev/db.conf)
DB_ASSET=$(tail -1 "$REPO_ROOT_DIR"/.fd2dev/db.conf)

echo "$FROM_REF"
echo "$TO_REF"
echo "$DB_VERSION"
echo "$DB_ASSET"

echo "Done."
