#!/bin/bash

# This post-checkout hook ensures the version of the sampleDB
# that is installed is compatible with the code in the branch.

REPO_ROOT_DIR=$(git rev-parse --show-toplevel)
source "$REPO_ROOT_DIR/bin/lib.bash"

FROM_REF=$1
TO_REF=$2

# Don't run this when a repo is cloned.
if [ -z "$FROM_REF" ]; then
  exit 0
fi

# Don't run this if there are no changes (e.g. switching to a new branch).
if [ "$FROM_REF" = "$TO_REF" ]; then
  exit 0
fi

# Don't run this unless we are in the FarmData2 repo.

echo "Running FarmData2 post-checkout hook..."

echo "$FROM_REF"
echo "$TO_REF"

echo "Done."
