<?php

use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Makes the FD2 icon available for the menus.
 */
function farm_fd2_page_attachments(&$variables) {
  $variables['#attached']['library'][] = 'farm_fd2/fd2_icon';
}

/**
 * Adds the fd2_harvest_units field to form and plant_type taxonomy terms.
 */
function farm_plant_type_entity_form_display_alter(EntityFormDisplayInterface $form_display, array $context) {
  if ($context['entity_type'] == 'taxonomy_term' && $context['bundle'] == 'plant_type') {
    $form_display->setComponent('fd2_harvest_units', [
      'type' => 'entity_reference',
      'settings' => [
        'target_type' => 'taxonomy_term'
      ],
      'region' => 'content',
      'weight' => 2,
    ]);
  }
}

function farm_plant_type_entity_view_display_alter(EntityViewDisplayInterface $display, array $context) {
  if ($context['entity_type'] == 'taxonomy_term' && $context['bundle'] == 'plant_type') {
    $display->setComponent('fd2_harvest_units', [
      'type' => 'entity_reference',
      'label' => 'inline',
      'settings' => [
        'target_type' => 'taxonomy_term'
      ],
      'region' => 'content',
      'weight' => 25,
    ]);
  }
}
