services:
  db:
    image: farmdata2/postgres:fd2.2
    container_name: fd2_postgres
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/postgresql/data
    networks:
      fd2_network:
        ipv4_address: 172.20.0.2
    ports:
      - '5432:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: farm
      POSTGRES_DB: farm

  farmos:
    depends_on:
      - db
    image: farmdata2/farmos3:fd2.1
    container_name: fd2_farmos
    volumes:
      # Mount a volume to hold the config information for farmos between runs.
      - type: volume
        source: farmos3_config_fd2.1
        target: /opt/drupal/web/sites
      # Mount the settings file for the reverse proxy
      - type: bind
        source: ./settings.php
        target: /opt/drupal/web/sites/default/settings.php
      # Mount the dist directories containing the fd2 modules into the farmOS container.
      - type: bind
        source: ../modules/farm_fd2/dist/farmdata2
        target: /opt/drupal/web/sites/all/modules/farmdata2
      - type: bind
        source: ../modules/farm_fd2_examples/dist/fd2_examples
        target: /opt/drupal/web/sites/all/modules/fd2_examples
      - type: bind
        source: ../modules/farm_fd2_school/dist/fd2_school
        target: /opt/drupal/web/sites/all/modules/fd2_school
    networks:
      fd2_network:
        ipv4_address: 172.20.0.3
    restart: unless-stopped
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: discover_client_host=yes

  proxy:
    depends_on:
      - farmos
    image: farmdata2/nginx:fd2.1
    container_name: fd2_nginx
    networks:
      fd2_network:
        ipv4_address: 172.20.0.4
    ports:
      - '443:443'
    volumes:
      - type: bind
        source: ./nginx.conf/nginx.deploy.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./ssl
        target: /etc/nginx/ssl
    restart: unless-stopped

volumes:
  farmos3_config_fd2.1:

networks:
  fd2_network:
    driver: bridge
    ipam:
      config:
        - subnet: '172.20.0.0/16'
          gateway: 172.20.0.1
